#!/bin/sh
cd /home/pi/drone/webapp/server

sleep 20

# Will only work on fast-forward merges
# echo "Calling git pull..." >> log
# sudo -u pi git pull >> log

echo "Starting server..." >> log
exec sudo python3 main.py >> log 2>&1
